import logging
import re

from openai import OpenAI

from app.core.config import Settings, get_settings
from app.models.lead import Lead

logger = logging.getLogger(__name__)


def generate_lead_summary(lead: Lead, settings: Settings | None = None) -> str | None:
    settings = settings or get_settings()

    try:
        client = OpenAI(
            base_url=settings.llm_base_url,
            api_key=settings.llm_api_key or "not-needed",
            max_retries=0,
            timeout=30.0,
        )
        response = client.chat.completions.create(
            model=settings.llm_model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an assistant for local business lead qualification. "
                        "Analyze the lead and return ONLY 4 short bullet points.\n\n"
                        "Format:\n"
                        "- Intent:\n"
                        "- Urgency:\n"
                        "- Key Need:\n"
                        "- Recommended Follow-up:\n\n"
                        "Rules:\n"
                        "- Maximum 1 short sentence per bullet\n"
                        "- No intro text\n"
                        "- No explanations\n"
                        "- Keep total output under 80 words\n"
                        "- Be concise and practical\n"
                        "- Do not mention that the summary was generated by AI\n"
                        "- Make it useful for a business owner or receptionist\n"
                        "- Output language must match the lead message language\n"
                        "- If the lead message is Romanian, write the summary in Romanian\n"
                        "- If the lead message is English, write the summary in English\n"
                        "- Do not use Chinese, Japanese, Korean, or any unrelated language\n"
                        "- Do not mix languages\n"
                        "- Return only the 4 required bullet points"
                    ),
                },
                {
                    "role": "user",
                    "content": _format_lead_for_prompt(lead),
                },
            ],
            temperature=0.2,
            max_tokens=120,
        )
        content = response.choices[0].message.content
    except Exception:
        logger.exception("Failed to generate lead summary")
        return None

    return _remove_cjk_characters(content).strip() if content else None


def _format_lead_for_prompt(lead: Lead) -> str:
    return "\n".join(
        [
            f"Name: {lead.name}",
            f"Phone: {lead.phone}",
            f"Email: {lead.email or 'Not provided'}",
            f"Service interest: {lead.service_interest or 'Not provided'}",
            f"Preferred date: {lead.preferred_date or 'Not provided'}",
            f"Message: {lead.message or 'Not provided'}",
        ]
    )


def _remove_cjk_characters(value: str) -> str:
    return re.sub(
        r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uac00-\ud7af\uf900-\ufaff]+",
        "",
        value,
    )
